GerenciamentoCatequese/Models/Catequisando.cs
namespace GerenciamentoCatequese.Models
{
    public class Catequisando
    {
        public int IdCatequisando { get; set; }
        public string? NomeCatequisando { get; set; }
        public DateTime? DataNascimento { get; set; } // Pode ser nulo
        public string? UFNaturalidade { get; set; }
        public string? MunicipioNaturalidade { get; set; }
        public bool Batizado { get; set; } // Pode ser nulo
        public DateTime? DataBatismo { get; set; }
        public string? UFBatismo { get; set; }
        public string? MunicipioBatismo { get; set; }
        public string? ParoquiBatismo { get; set; }
        public bool Eucaristia { get; set; } // Pode ser nulo
        public DateTime? DataEucaristia { get; set; }
        public string? UFEucatistia { get; set; }
        public string? MunicipioEucaristia { get; set; }
        public string? ParoquiaEucaristia { get; set; }
        public bool Pastoral { get; set; } // Pode ser nulo
        public string? DescricaoPastoral { get; set; }
        public string? CepEndereco { get; set; }
        public string? UFEndereco { get; set; }
        public string? LogradouroEndereco { get; set; }
        public string? BairroEndereco { get; set; }
        public string? CidadeEndereco { get; set; }
        public string? NumeroEndereco { get; set; }
        public string? ComplementoEndereco { get; set; }
        public string? Email { get; set; }
        public string? TelefoneResidencial { get; set; }
        public string? TelefoneCelular { get; set; }
        public int IdTurma { get; set; }
        public int Idade { get; set; }
        public string? DescricaoTurma { get; set; }
        public int AnoCatequese { get; set; }
    }


}

GerenciamentoCatequese/Models/Catequista.cs
namespace GerenciamentoCatequese.Models
{
    public class Catequista
    {
        public int idCatequista { get; set; }
        public int IdTurma { get; set; }
        public string? NomeCatequista { get; set; }
        public DateTime? DataNascimento { get; set; }
        public string? Email { get; set; }
        public string? Telefone { get; set; }
        public string? Endereco { get; set; }
        public int IdPerfil { get; set; }
        public int Trabalha { get; set; }
        public string? Profissao { get; set; }
        public string? Disponibilidade { get; set; }
        public string? TamanhoCamiseta { get; set; }
        public string? EstadoCivil { get; set; }
        public int? Pastoral { get; set; }
        public string? DescricaoPastoral { get; set; }
        public string? Senha { get; set; }
        public string? DescricaoTurma { get; set; }
        public string? DescricaoPerfil { get; set; }
        public string? Foto { get; set; }
        public int Batismo { get; set; }
        public int Eucaristia { get; set; }
        public int Crisma { get; set; }
        public int Matrimonio { get; set; }
        public List<SacaramentosCatequista>? Sacramentos { get; set; }
    }
}

GerenciamentoCatequese/Models/PagamentoTaxa.cs
namespace GerenciamentoCatequese.Models
{
    public class PagamentoTaxa
    {
        public int IdCatequisando { get; set; }
        public int IdTurma { get; set; }
        public string? Parcela { get; set; }
        public DateTime DataPagamento { get; set; }
        public string? ValorPagamento { get; set; }
        public string? NomeResponsavel { get; set; }
    }
}

GerenciamentoCatequese/Models/RelatorioFrequenciaLancada.cs
namespace GerenciamentoCatequese.Models
{
    public class RelatorioFrequenciaLancada
    {
        public string? DescricaoTurma { get; set; }
        public DateTime DataFrequencia { get; set; }

    }
}

GerenciamentoCatequese/Pages/Catequistas.cshtml.cs
using GerenciamentoCatequese.Interfaces;
using GerenciamentoCatequese.Models;
using GerenciamentoCatequese.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace GerenciamentoCatequese.Pages
{
    public class CatequistaModel : PageModel
    {
        private readonly IGerenciamentoService _gerenciamento;
        public IEnumerable<Catequista> _catequistas { get; set; } = Enumerable.Empty<Catequista>();

        public CatequistaModel(IGerenciamentoService gerenciamento)
        {
            _gerenciamento = gerenciamento;
        }

        public async Task<IActionResult> OnGet()
        {
            _catequistas = await _gerenciamento.ListarCatequistas();

            return Page();
        }
    }
}

GerenciamentoCatequese/Pages/DetalhesCatequisando.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GerenciamentoCatequese.Interfaces;
using GerenciamentoCatequese.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GerenciamentoCatequese.Pages
{
   
    public class DetalhesCatequisandoModel : PageModel
    {
        [BindProperty]
        public Catequisando _catequisando { get; set; } = new();

        public IEnumerable<ResponsavelCatequisando> _responsaveisCatequisando = Enumerable.Empty<ResponsavelCatequisando>();
        public IEnumerable<DocumentosEntregues> _documentos { get; set; } = Enumerable.Empty<DocumentosEntregues>();
        public DadosPagamento _pagamentos { get; set; } = new();

        [BindProperty]
        public string _ObservacoesGerais { get; set; } = "";

        [BindProperty(SupportsGet = true)]
        public int IdCatequisandoDetalhes { get; set; } = new();

        private readonly IGerenciamentoService _gerenciamento;

        public DetalhesCatequisandoModel(IGerenciamentoService gerenciamento)
        {
            _gerenciamento = gerenciamento;
        }

        public async Task<IActionResult> OnGet()
        {
            if (IdCatequisandoDetalhes != 0)
            {
                _catequisando = await _gerenciamento.PesquisaCatequisando(IdCatequisandoDetalhes);
                _responsaveisCatequisando = await _gerenciamento.ListarResponsaveisCatequisando(IdCatequisandoDetalhes);
                _ObservacoesGerais = await _gerenciamento.ListarObservacoes(IdCatequisandoDetalhes);
                _documentos = await _gerenciamento.ListarDocumentosEntregues(IdCatequisandoDetalhes);
                _pagamentos = await _gerenciamento.ListarDadosPagamento(IdCatequisandoDetalhes);
            }

            return Page();
        }
    }
}

GerenciamentoCatequese/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GerenciamentoCatequese.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

GerenciamentoCatequese/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GerenciamentoCatequese.Pages
{
    [AllowAnonymous]
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnPost()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/login");
        }
    }
}

GerenciamentoCatequese/Pages/PagamentoTaxa.cshtml.cs
using GerenciamentoCatequese.Interfaces;
using GerenciamentoCatequese.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GerenciamentoCatequese.Pages
{
    public class PagamentoTaxaModel : PageModel
    {
        [BindProperty]
        public PagamentoTaxa _pagamentoTaxa { get; set; }

        [BindProperty(SupportsGet = true)]
        public int IdCatequisando { get; set; } = new();

        private readonly IGerenciamentoService _gerenciamentoService;
        public Catequisando _catequisando { get; set; } = new();
        public IEnumerable<ResponsavelCatequisando> _responsaveis { get; set; } = Enumerable.Empty<ResponsavelCatequisando>();
        public IEnumerable<RegistroPagamentosTaxa> _registroPagamentosTaxas { get; set; } = Enumerable.Empty<RegistroPagamentosTaxa>();

        public IEnumerable<Turma> _turmas { get; set; } = Enumerable.Empty<Turma>();
        public PagamentoTaxaModel(IGerenciamentoService gerenciamentoService)
        {
            _gerenciamentoService = gerenciamentoService;
        }

        public async Task<IActionResult> OnGet()
        {
            _registroPagamentosTaxas = await _gerenciamentoService.ListarRegistrosPagamentosTaxa(IdCatequisando);
            _turmas = await _gerenciamentoService.ListarTurmas();
            _catequisando = await _gerenciamentoService.PesquisaCatequisando(IdCatequisando);
           _responsaveis = await _gerenciamentoService.ListarResponsaveisCatequisando(IdCatequisando);

            return Page();
        }

        public async Task<IActionResult> OnPostEnviarFormulario()
        {

            var retorno = await _gerenciamentoService.GravarPagamentoTaxa(_pagamentoTaxa);

            return RedirectToPage("PagamentoTaxa", new { IdCatequisando = _pagamentoTaxa.IdCatequisando});
        }

     
    }
}

GerenciamentoCatequese/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GerenciamentoCatequese.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

GerenciamentoCatequese/Pages/RelatorioFrequenciaLancada.cshtml.cs
using GerenciamentoCatequese.Interfaces;
using GerenciamentoCatequese.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace GerenciamentoCatequese.Pages
{
    public class RelatorioFrequenciaLancadaModel(IGerenciamentoService gerenciamentoService) : PageModel
    {

        public IEnumerable<RelatorioFrequenciaLancada> _frequencias = Enumerable.Empty<RelatorioFrequenciaLancada>();
        public async Task<IActionResult> OnGet()
        {
            _frequencias = await gerenciamentoService.GerarRelatorioFrequenciaLancada();

            return Page();
        }
    }
}

GerenciamentoCatequese/Pages/RelatorioPagamento.cshtml.cs
using GerenciamentoCatequese.Interfaces;
using GerenciamentoCatequese.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GerenciamentoCatequese.Pages
{
    public class RelatorioPagamentoModel (IGerenciamentoService gerenciamentoService, IFileManager file) : PageModel
    {

        public IEnumerable<RelatorioPagamentoTaxa> _pagamentos = Enumerable.Empty<RelatorioPagamentoTaxa>();

        public async Task<IActionResult> OnGet()
        {
            _pagamentos = await gerenciamentoService.GerarRelatorioPagamentoTaxa();

            return Page();
        }

        public async Task<IActionResult> OnPostGerarRelatorioPagamentoTaxa()
        {
            var retorno = await gerenciamentoService.GerarRelatorioPagamentoTaxa();

            var retornoExcel = await file.GerarExcelPagamentoTaxa(retorno);

            var retornoArquivo = await file.GerarArquivo(retornoExcel);

            var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            var fileName = "RelatorioPagamentoTaxa.xlsx";

            return File(retornoArquivo, contentType, fileName);
        }

        public async Task<IActionResult> OnPostDeletarPagamentoTaxa(int IdPagamentoTaxaExclusao)
        {
            await gerenciamentoService.DeletarPagamentoTaxa(IdPagamentoTaxaExclusao);
            return RedirectToPage("RelatorioPagamento");
        }

        
    }
}

GerenciamentoCatequese/Pages/Catequistas.cshtml
@page
@model GerenciamentoCatequese.Pages.CatequistaModel
@{
}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/datagrid.css" rel="stylesheet" />
    <title>Catequese</title>

</head>

<body>
    <div class="mt-4">
        <h1 style="text-align: center">Catequese PNSD</h1>
    </div>

    <div class="page-wrapper mt-3">
        <!-- BEGIN PAGE HEADER -->
        <div class="page-header d-print-none">
            <div class="container-xl">
                <div class="row g-2 align-items-center">
                    <div class="col">
                        <h2 class="page-title">Catequistas</h2>
                    </div>
                    <!-- Page title actions -->
                    <div class="col-auto ms-auto d-print-none">
                        <div class="d-flex">
                            <input type="search" class="form-control d-inline-block w-9 me-3" placeholder="Pesquisar">
                            <a href="./catequistaCadastro" class="btn btn-primary btn-3">
                                <!-- Download SVG icon from http://tabler.io/icons/icon/plus -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-2">
                                    <path d="M12 5l0 14"></path>
                                    <path d="M5 12l14 0"></path>
                                </svg>
                                Adicionar catequista
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE HEADER -->
        <!-- BEGIN PAGE BODY -->
        <div class="page-body">
            <div class="container-xl">
                <div class="row row-cards">
                    @foreach (var item in Model._catequistas)
                    {
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body p-4 text-center">
                                    <img class="avatar avatar-xl mb-3" src="@item.Foto" />
                                    <h3 class="m-0 mb-1"><a href="#">@item.NomeCatequista</a></h3>
                                    <div class="text-secondary">@item.DescricaoTurma</div>
                                    <div class="mt-3">
                                        @if (item.DescricaoPerfil == "Catequista")
                                        {
                                            <span class="badge bg-green-lt">@item.DescricaoPerfil</span>
                                        }
                                        else if (item.DescricaoPerfil == "Líder")
                                        {
                                            <span class="badge bg-purple-lt">@item.DescricaoPerfil</span>
                                        }
                                        else
                                        {
                                            <span class="badge bg-red-lt">@item.DescricaoPerfil</span>
                                        }
                                    </div>
                                </div>
                                <div class="d-flex">
                                    <a href="#" class="card-btn">
                                        <svg style="margin-right:2px" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-search">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                            <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" />
                                            <path d="M21 21l-6 -6" />
                                        </svg>
                                        Detalhes
                                    </a>
                                    <input type="hidden" value="@item.idCatequista" class="id-Catequista" id="idCatequistaEditar" />
                                    <a href="#" class="card-btn edit-catequista">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-edit">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                            <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                                            <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                                            <path d="M16 5l3 3" />
                                        </svg>
                                        Editar
                                    </a>

                                </div>
                            </div>
                        </div>
                    }


                </div>
            </div>
        </div>
    </div>
</body>
</html>


<script>
        document.addEventListener('DOMContentLoaded', function () {
        const editButtons = document.querySelectorAll('.edit-catequista');

        editButtons.forEach(button => {
            button.addEventListener('click', function (event) {
                event.preventDefault();

                const idCatequista = this.parentElement.querySelector('.id-Catequista').value;

                window.location.href = `./CatequistaCadastro?IdCatequistaEditar=${idCatequista}`;
            });
        });
    });

</script>

GerenciamentoCatequese/Pages/Logout.cshtml
@page
@model GerenciamentoCatequese.Pages.LogoutModel
@{
}

GerenciamentoCatequese/Pages/RelatorioFrequenciaLancada.cshtml
@page
@model GerenciamentoCatequese.Pages.RelatorioFrequenciaLancadaModel
@{
}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciamento</title>

</head>


<body>
    <div class="mt-4">
        <h1 style="text-align: center">Catequese PNSD 2025</h1>
    </div>
    <div class="mt-4">
        <div class=" card card-md container-narrow py-2 px-2">
            <div class="card-body">

                <div class="container-xl mb-4">
                    <div class="mb-3 div-itens" style="display: flex; justify-content: space-between; align-items: center;">
                        <h3 class="titulo-card">Relatório de pagamento das taxas</h3>
                        <div style="display:flex">

                            <form method="post" asp-page-handler="GerarRelatorioPagamentoTaxa">
                                <button type="submit" class="btn btn-6 btn-primary active w-20 btn-custom">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-download">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2" />
                                        <path d="M7 11l5 5l5 -5" />
                                        <path d="M12 4l0 12" />
                                    </svg>
                                    Gerar Relatorio
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="row mb-3">
                                    <div class="col-md-6 mb-2">
                                        <input type="text" id="searchNome" class="form-control" placeholder="Filtrar por Nome">
                                    </div>
                                    <div class="col-md-6 mb-2">
                                        <select id="filterTurma" class="form-control">
                                            <option value="">Todas as Turmas</option>
                                        </select>
                                    </div>
                                </div>

                            </div>

                            <div class="table-responsive">
                                <table class="table table-vcenter card-table table-striped" id="tableData">
                                    <thead>
                                        <tr>
                                            <th>Turma</th>
                                            <th>Data</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody id="tabela-body-Relatorio-FrequenciaLancada">
                                        @foreach (var item in Model._frequencias)
                                        {
                                            <tr>
                                                <td class="col-turma text-secondary">@item.DescricaoTurma</td>
                                                <td class="col-data text-secondary">@item.DataFrequencia</td>
                                                <td>
                                                    <div class="btn-list flex-nowrap">
                                                        <div class="dropdown">
                                                            <button class="btn dropdown-toggle align-text-top" data-bs-toggle="dropdown">
                                                                Ações
                                                            </button>
                                                            <div class="exclusao dropdown-menu dropdown-menu-end">
                                                                <a style="cursor: pointer;" class="dropdown-item" onclick="abrirModalExclusao(this);">
                                                                    Excluir
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>

                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                            <div class="d-flex justify-content-between align-items-center mt-3 mb-3">
                                <button id="btnPrev" style="margin-left:10px" class="btn btn-primary">
                                    <svg style="margin-left:0px; margin-right:5px" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-left">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M15 6l-6 6l6 6" />
                                    </svg>
                                    Anterior
                                </button>
                                <span id="page-info" class="fw-bold"></span>
                                <button id="btnNext" style="margin-right:10px" class="btn btn-primary">
                                    Próximo
                                    <svg style="margin-left:5px; margin-right:0px" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-right">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M9 6l6 6l-6 6" />
                                    </svg>
                                </button>
                            </div>




                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal modal-blur fade" id="modalExcluirPagamento" tabindex="-1" style="display: none; opacity:revert; z-index: 8001;" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
            <div class="modal-content">
                <form method="post" asp-page-handler="DeletarPagamentoTaxa">
                    <div class="modal-status bg-danger"></div>
                    <div class="modal-body text-center py-4">
                        <!-- Download SVG icon from http://tabler.io/icons/icon/alert-triangle -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon mb-2 text-danger icon-lg"><path d="M12 9v4"></path><path d="M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0z"></path><path d="M12 16h.01"></path></svg>
                        <h3>Atenção</h3>
                        <div class="text-secondary">Tem certeza que deja excluir o pagamento?</div>
                    </div>
                    <div class="modal-footer">
                        <div class="w-100">
                            <div class="row">
                                <div class="col">
                                    <a href="#" class="btn btn-3 w-100" data-bs-dismiss="modal">
                                        Cancelar
                                    </a>
                                </div>
                                <div class="col">
                                    <input type="hidden" name="IdPagamentoTaxaExclusao" id="idParaExcluir" />
                                    <button type="submit" id="confirmarFinalizar" class="btn btn-warning btn-4 w-100" data-bs-dismiss="modal">
                                        Confirmar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


</body>
</html>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const filterTurma = document.getElementById("filterTurma");
        const table = document.getElementById("tabela-body-Relatorio-FrequenciaLancada");
        const tableRows = Array.from(table.getElementsByTagName("tr"));

        const pageSize = 5;
        let currentPage = 1;
        let filteredRows = [...tableRows];

        // Criar lista única de turmas e preencher o select
        const turmas = new Set();
        tableRows.forEach(row => {
            const turma = row.querySelector(".col-turma")?.textContent.trim();
            if (turma) turmas.add(turma);
        });
        turmas.forEach(turma => {
            const option = document.createElement("option");
            option.value = turma;
            option.textContent = turma;
            filterTurma.appendChild(option);
        });

        function showPage(page) {
            const totalPages = Math.ceil(filteredRows.length / pageSize);
            currentPage = Math.min(Math.max(page, 1), totalPages || 1);

            tableRows.forEach(row => row.style.display = "none");

            filteredRows.slice((currentPage - 1) * pageSize, currentPage * pageSize)
                .forEach(row => row.style.display = "table-row");

            document.getElementById("page-info").textContent = `Página ${currentPage} de ${totalPages || 1}`;
        }

        function filtrarTabela() {
            const turmaFiltro = filterTurma.value;

            filteredRows = tableRows.filter(row => {
                const turma = row.querySelector(".col-turma")?.textContent.trim();

                return turmaFiltro === "" || turma === turmaFiltro;
            });

            currentPage = 1;
            showPage(currentPage);
        }

        filterTurma.addEventListener("change", filtrarTabela);

        document.getElementById("btnNext").addEventListener("click", () => {
            if (currentPage < Math.ceil(filteredRows.length / pageSize)) {
                showPage(currentPage + 1);
            }
        });
        document.getElementById("btnPrev").addEventListener("click", () => {
            if (currentPage > 1) {
                showPage(currentPage - 1);
            }
        });

        showPage(1); // Exibir primeira página ao carregar
    });

    // Função para abrir o modal e popular o campo hidden com o ID da linha clicada
    function abrirModalExclusao(elemento) {
        const dropdown = elemento.closest(".dropdown-menu");
        const idPagamento = dropdown.querySelector(".id-documento").value;
        document.getElementById("idParaExcluir").value = idPagamento;

        const modal = new bootstrap.Modal(document.getElementById("modalExcluirPagamento"));
        modal.show();
    }
</script>